### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by xwh8965** [MoonLeeeaf/EdgeNewTab#1]
哥在吗 请问下可以帮忙定制一个模块功能吗，有预算。

**Comment by MoonLeeeaf** [comment]
很抱歉但是我没有这个精力去投入实际开发，并且我没有这个能力

这边建议自己学习下如何开发模块，并多参考实际项目

**Comment by MoonLeeeaf** [comment]
另外不需要这样到处开 Issue，会打扰到他们，而且我们的时间不足以进行开发，就算有进度会非常缓慢甚至停止一段时间，建议自己学习，甚至使用参考代码进行修改（当然不要拿已有项目，除非你知道如何处理开源许可证的问题）

**Comment by MoonLeeeaf** [comment]
看了下你开的Issue 可能你要开发QQ模块吧
开发QQ模块比较费时，因此我还是建议你使用已有的模块，如果有代码基础，可以仿照他人的代码开PR或者Issue并给出样例代码
